### ISSUE TITLE
About customer data model

### ISSUE THREAD

**Issue by bluestraenje** [ProximaCentauri/IntDesign#12]
1. Can a customer have more than 1 bank?
2. Can a customer have more than 1 contact number?
3. Can a customer have more than 1 email address?
4. Can a customer have more than 1 valid Ids?

**Comment by vanznav** [comment]
Can a customer have more than 1 bank?
- yes
  Can a customer have more than 1 contact number?
- yes and can define what type of contact number. same with iphone on adding contact number
  Can a customer have more than 1 email address?
- yes
  Can a customer have more than 1 valid Ids?
- yes
