### ISSUE TITLE
About the user data model

### ISSUE THREAD

**Issue by bluestraenje** [ProximaCentauri/IntDesign#13]
1. How many users do we need to support?
2. Can a user add a utility bill?
3. Mapping of users to roles/access rights.

**Comment by vanznav** [comment]
How many users do we need to support?
- no exact number. but we can have 2 admin and 2 guest users
  Can a user add a utility bill?
- yes
  Mapping of users to roles/access rights.
- guest users only has read access. probably can add utility bills and payments but need to confirm
