### ISSUE TITLE
Grid will update when changing value in LastName, FirstName...textbox

### ISSUE THREAD

**Issue by marzim** [ProximaCentauri/IntDesign#39]
Grid will update when changing value in LastName, FirstName..etc even though you haven't save it yet.

Steps to reproduce:
- Select customer in the grid
- Change the LastName field
- Select another field.
- Noticed that the LastName in the Grid will change based on the value you change

Expectation: It shouldn't since you haven't save it yet.

**Comment by bluestraenje** [comment]
issue fixed
