### ISSUE TITLE
Provide validations on fields 

### ISSUE THREAD

**Issue by bluestraenje** [ProximaCentauri/IntDesign#44]
1. Personal information
   -- first name, last name, address, mobile number / landline number
   -- if with dependent - first name, and last name of dependent
   -- if with spouse - name of spouse
2. Bank
   -- all fields required
3. Utility
   -- bill type, company name, subscriber name, account #
   -- for bill type - name is required
   -- for company name - bill type and name are both required

**Comment by marzim** [comment]
Already done with the validation listed here.
