### ISSUE TITLE
Reset Password - Temporary PIN and email address are not cleared

### ISSUE THREAD

**Issue by bluestraenje** [ProximaCentauri/IntDesign#66]
1. Generate PIN
2. Go to reset password, and enter email add and pin.
3. Click on submit
4. On new password / confirm password screen, click on X button. Do not enter new password.
5. Click on Reset password again.

Actual result - email address and temporary pin have the previous values
Expected result - email address and temporary pin input fields should be empty.

**Comment by vanznav** [comment]
fix issue in the latest build.
