### ISSUE TITLE
Crash issue while trying to Save details

### ISSUE THREAD

**Issue by marzim** [ProximaCentauri/IntDesign#71]
- Add dependent then remove
- Add Bank then remove
- Add appliance then remove
- Add utility then remove
- Add payment then remove
- Click Save Details button

![image](https://cloud.githubusercontent.com/assets/820465/20552955/10b7e1ae-b18b-11e6-9100-cb6da7023d34.png)

**Comment by bluestraenje** [comment]
fixed in latest build
